Repository Edmir-Demaj/hackathon-june-23, pull requests merged in 2023-06, with the labels that each got.

#18 Fix merge conflicts with duplicate files
  static/css/style.css
  templates/base.html
Labels: bug, enhancement

#19 Add: Index.html content and background colour
  main_app/templates/main_app/index.html
  static/css/style.css
  static/favicon.ico
  static/media/logo.png
  templates/base.html
Labels: enhancement

#23 Kim
  main_app/templates/main_app/contact.html
Labels: documentation

#28 Jody m
  main_app/templates/main_app/index.html
  static/css/style.css
Labels: enhancement

#32 README.md configuration from Ignas branch
  README.md
Labels: documentation

#30 Javascript function along with latest style change on contact page
  main_app/templates/main_app/contact.html
  main_app/templates/main_app/resources.html
  static/js/script.js
Labels: documentation, function

#33 Added the last thing on contact page, css file and update readme
  README.md
  main_app/templates/main_app/contact.html
  static/css/style.css
  static/media/readme-jshint.jpg
Labels: documentation

#34 Add: media query for smallest screen sizes for home screen
  static/css/style.css
  static/js/script.js
Labels: enhancement

#35 Jody m
  static/js/script.js
  templates/base.html
Labels: bug
